/-
Copyright 2026 Overclock Validator
SPDX-License-Identifier: Apache-2.0

Generated by tools/generate_r51_linear_trace.py from src/r51x8_ifma.S.
Do not edit by hand. The generator accepts only the exact straight-line add,
subtract, negate, NORMALIZE_5, load/store, and constant shapes modeled here.
This is a source trace, not an emitted-object or x86 ISA refinement.
-/

import NaryaFormal.Radix51

namespace NaryaFormal.Radix51.GeneratedR51LinearTrace

def sourceMask : Nat := 2251799813685247
def sourceFold : Nat := 19
def sourceBias0 : Nat := 9007199254740916
def sourceBiasN : Nat := 9007199254740988

def addRaw (x y : Loose5) : Loose5 :=
  { l0 := x.l0 + y.l0
    l1 := x.l1 + y.l1
    l2 := x.l2 + y.l2
    l3 := x.l3 + y.l3
    l4 := x.l4 + y.l4 }

def subRaw (x y : Loose5) : Loose5 :=
  { l0 := x.l0 + sourceBias0 - y.l0
    l1 := x.l1 + sourceBiasN - y.l1
    l2 := x.l2 + sourceBiasN - y.l2
    l3 := x.l3 + sourceBiasN - y.l3
    l4 := x.l4 + sourceBiasN - y.l4 }

def negRaw (x : Loose5) : Loose5 :=
  { l0 := sourceBias0 - x.l0
    l1 := sourceBiasN - x.l1
    l2 := sourceBiasN - x.l2
    l3 := sourceBiasN - x.l3
    l4 := sourceBiasN - x.l4 }

def addOutput (x y : Loose5) : Loose5 := normalized (addRaw x y)
def subOutput (x y : Loose5) : Loose5 := normalized (subRaw x y)
def negOutput (x : Loose5) : Loose5 := normalized (negRaw x)

end NaryaFormal.Radix51.GeneratedR51LinearTrace
