/-
Copyright 2026 Overclock Validator
SPDX-License-Identifier: Apache-2.0

GENERATED FILE. DO NOT EDIT.
Generated by tools/generate_r51_mul_trace.py from src/r51x8_ifma.S.
The definitions below are proof inputs, not an independent oracle.
-/

import NaryaFormal.Radix51

namespace NaryaFormal.Radix51.GeneratedR51MulTrace

def sourceLoadOffsets : List Nat := [0, 64, 128, 192, 256]
def outputStoreOffsets : List Nat := [0, 64, 128, 192, 256]
def foldConstant : Nat := 19
def traceMask : Nat := 2251799813685247
def traceCarry (value : Nat) : Nat := value / (2 ^ 51)
def traceRemainder (value : Nat) : Nat := value % (2 ^ 51)

def lowTerms (x y : FiveLimbs) : Nat -> List Nat
  | 0 => [lo52 (x 0) (y 0)]
  | 1 => [lo52 (x 0) (y 1), lo52 (x 1) (y 0)]
  | 2 => [lo52 (x 0) (y 2), lo52 (x 1) (y 1), lo52 (x 2) (y 0)]
  | 3 => [lo52 (x 0) (y 3), lo52 (x 1) (y 2), lo52 (x 2) (y 1), lo52 (x 3) (y 0)]
  | 4 => [lo52 (x 0) (y 4), lo52 (x 1) (y 3), lo52 (x 2) (y 2), lo52 (x 3) (y 1), lo52 (x 4) (y 0)]
  | 5 => [lo52 (x 1) (y 4), lo52 (x 2) (y 3), lo52 (x 3) (y 2), lo52 (x 4) (y 1)]
  | 6 => [lo52 (x 2) (y 4), lo52 (x 3) (y 3), lo52 (x 4) (y 2)]
  | 7 => [lo52 (x 3) (y 4), lo52 (x 4) (y 3)]
  | 8 => [lo52 (x 4) (y 4)]
  | _ => []

def highTerms (x y : FiveLimbs) : Nat -> List Nat
  | 0 => [hi52 (x 0) (y 0)]
  | 1 => [hi52 (x 0) (y 1), hi52 (x 1) (y 0)]
  | 2 => [hi52 (x 0) (y 2), hi52 (x 1) (y 1), hi52 (x 2) (y 0)]
  | 3 => [hi52 (x 0) (y 3), hi52 (x 1) (y 2), hi52 (x 2) (y 1), hi52 (x 3) (y 0)]
  | 4 => [hi52 (x 0) (y 4), hi52 (x 1) (y 3), hi52 (x 2) (y 2), hi52 (x 3) (y 1), hi52 (x 4) (y 0)]
  | 5 => [hi52 (x 1) (y 4), hi52 (x 2) (y 3), hi52 (x 3) (y 2), hi52 (x 4) (y 1)]
  | 6 => [hi52 (x 2) (y 4), hi52 (x 3) (y 3), hi52 (x 4) (y 2)]
  | 7 => [hi52 (x 3) (y 4), hi52 (x 4) (y 3)]
  | 8 => [hi52 (x 4) (y 4)]
  | _ => []

def groupedDegree (x y : FiveLimbs) : Nat -> Nat
  | 0 => (lowTerms x y 0).sum
  | 1 => ((lowTerms x y 1).sum) + (2 * ((highTerms x y 0).sum))
  | 2 => ((lowTerms x y 2).sum) + (2 * ((highTerms x y 1).sum))
  | 3 => ((lowTerms x y 3).sum) + (2 * ((highTerms x y 2).sum))
  | 4 => ((lowTerms x y 4).sum) + (2 * ((highTerms x y 3).sum))
  | 5 => ((lowTerms x y 5).sum) + (2 * ((highTerms x y 4).sum))
  | 6 => ((lowTerms x y 6).sum) + (2 * ((highTerms x y 5).sum))
  | 7 => ((lowTerms x y 7).sum) + (2 * ((highTerms x y 6).sum))
  | 8 => ((lowTerms x y 8).sum) + (2 * ((highTerms x y 7).sum))
  | 9 => 2 * ((highTerms x y 8).sum)
  | _ => 0

def foldedGrouped (x y : FiveLimbs) : Loose5 :=
  { l0 := ((lowTerms x y 0).sum) + foldConstant * (((lowTerms x y 5).sum) + (2 * ((highTerms x y 4).sum)))
    l1 := (((lowTerms x y 1).sum) + (2 * ((highTerms x y 0).sum))) + foldConstant * (((lowTerms x y 6).sum) + (2 * ((highTerms x y 5).sum)))
    l2 := (((lowTerms x y 2).sum) + (2 * ((highTerms x y 1).sum))) + foldConstant * (((lowTerms x y 7).sum) + (2 * ((highTerms x y 6).sum)))
    l3 := (((lowTerms x y 3).sum) + (2 * ((highTerms x y 2).sum))) + foldConstant * (((lowTerms x y 8).sum) + (2 * ((highTerms x y 7).sum)))
    l4 := (((lowTerms x y 4).sum) + (2 * ((highTerms x y 3).sum))) + foldConstant * (2 * ((highTerms x y 8).sum)) }

def assemblyOutput (x y : FiveLimbs) : Loose5 :=
  { l0 := traceRemainder (((lowTerms x y 0).sum) + foldConstant * (((lowTerms x y 5).sum) + (2 * ((highTerms x y 4).sum)))) + lo52 foldConstant (traceCarry ((((lowTerms x y 4).sum) + (2 * ((highTerms x y 3).sum))) + foldConstant * (2 * ((highTerms x y 8).sum))))
    l1 := traceRemainder ((((lowTerms x y 1).sum) + (2 * ((highTerms x y 0).sum))) + foldConstant * (((lowTerms x y 6).sum) + (2 * ((highTerms x y 5).sum)))) + traceCarry (((lowTerms x y 0).sum) + foldConstant * (((lowTerms x y 5).sum) + (2 * ((highTerms x y 4).sum))))
    l2 := traceRemainder ((((lowTerms x y 2).sum) + (2 * ((highTerms x y 1).sum))) + foldConstant * (((lowTerms x y 7).sum) + (2 * ((highTerms x y 6).sum)))) + traceCarry ((((lowTerms x y 1).sum) + (2 * ((highTerms x y 0).sum))) + foldConstant * (((lowTerms x y 6).sum) + (2 * ((highTerms x y 5).sum))))
    l3 := traceRemainder ((((lowTerms x y 3).sum) + (2 * ((highTerms x y 2).sum))) + foldConstant * (((lowTerms x y 8).sum) + (2 * ((highTerms x y 7).sum)))) + traceCarry ((((lowTerms x y 2).sum) + (2 * ((highTerms x y 1).sum))) + foldConstant * (((lowTerms x y 7).sum) + (2 * ((highTerms x y 6).sum))))
    l4 := traceRemainder ((((lowTerms x y 4).sum) + (2 * ((highTerms x y 3).sum))) + foldConstant * (2 * ((highTerms x y 8).sum))) + traceCarry ((((lowTerms x y 3).sum) + (2 * ((highTerms x y 2).sum))) + foldConstant * (((lowTerms x y 8).sum) + (2 * ((highTerms x y 7).sum)))) }

end NaryaFormal.Radix51.GeneratedR51MulTrace
