/*
 * Copyright 2026 Overclock Validator
 * SPDX-License-Identifier: Apache-2.0
 *
 * Cross-implementation decoder differential.
 *
 * The expected points are generated by the pinned scalar Go decoder described
 * in tests/vectors/README.md.  This test does not reuse the C decoder's field
 * equations to construct its answers: it reads complete affine/extended point
 * coordinates from the fixture, executes eight unrelated byte strings in the
 * native lane layout, and compares each coordinate modulo p.
 */
#include "internal.h"

#include <errno.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct decode_vector {
    uint8_t encoded[32];
    int valid;
    uint64_t coordinate[4][5];
} decode_vector;

static void
canonical_lane(uint64_t out[5], const narya_r51x8 *in, size_t lane)
{
    const uint64_t mask51 = (UINT64_C(1) << 51) - 1;
    for (size_t limb = 0; limb < 5; limb++)
        out[limb] = in->limb[limb][lane];
    for (unsigned int round = 0; round < 4; round++) {
        for (size_t limb = 0; limb < 4; limb++) {
            const uint64_t carry = out[limb] >> 51;
            out[limb] &= mask51;
            out[limb + 1] += carry;
        }
        const uint64_t carry = out[4] >> 51;
        out[4] &= mask51;
        out[0] += 19 * carry;
    }
    if (out[1] == mask51 && out[2] == mask51 &&
        out[3] == mask51 && out[4] == mask51 &&
        out[0] >= mask51 - 18) {
        out[0] -= mask51 - 18;
        out[1] = out[2] = out[3] = out[4] = 0;
    }
}

static int
equal_field_lane(const narya_r51x8 *a, const narya_r51x8 *b, size_t lane)
{
    uint64_t canonical_a[5];
    uint64_t canonical_b[5];
    canonical_lane(canonical_a, a, lane);
    canonical_lane(canonical_b, b, lane);
    uint64_t diff = 0;
    for (size_t limb = 0; limb < 5; limb++)
        diff |= canonical_a[limb] ^ canonical_b[limb];
    return diff == 0;
}

static int
hex_nibble(char c)
{
    if (c >= '0' && c <= '9')
        return c - '0';
    if (c >= 'a' && c <= 'f')
        return c - 'a' + 10;
    if (c >= 'A' && c <= 'F')
        return c - 'A' + 10;
    return -1;
}

static int
parse_encoded(uint8_t out[32], const char *text)
{
    if (strlen(text) != 64)
        return 0;
    for (size_t i = 0; i < 32; i++) {
        const int high = hex_nibble(text[2 * i]);
        const int low = hex_nibble(text[2 * i + 1]);
        if (high < 0 || low < 0)
            return 0;
        out[i] = (uint8_t)((high << 4) | low);
    }
    return 1;
}

static char *
next_token(char **cursor)
{
    char *start = *cursor;
    while (*start == ' ' || *start == '\t')
        start++;
    if (*start == '\0' || *start == '\n')
        return NULL;
    char *end = start;
    while (*end != '\0' && *end != '\n' && *end != ' ' && *end != '\t')
        end++;
    if (*end != '\0')
        *end++ = '\0';
    *cursor = end;
    return start;
}

static int
parse_vector(char *line, decode_vector *out)
{
    char *cursor = line;
    char *token = next_token(&cursor);
    if (token == NULL || !parse_encoded(out->encoded, token))
        return 0;

    token = next_token(&cursor);
    if (token == NULL || (strcmp(token, "0") != 0 && strcmp(token, "1") != 0))
        return 0;
    out->valid = token[0] - '0';

    for (size_t coordinate = 0; coordinate < 4; coordinate++) {
        for (size_t limb = 0; limb < 5; limb++) {
            token = next_token(&cursor);
            if (token == NULL)
                return 0;
            errno = 0;
            char *end = NULL;
            const uintmax_t value = strtoumax(token, &end, 16);
            if (errno != 0 || end == token || *end != '\0' ||
                value >= (UINT64_C(1) << 51))
                return 0;
            out->coordinate[coordinate][limb] = (uint64_t)value;
        }
    }
    return next_token(&cursor) == NULL;
}

static void
set_expected_lane(narya_edwards_point_x8 *point, size_t lane, const decode_vector *vector)
{
    narya_r51x8 *coordinates[4] = {&point->X, &point->Y, &point->Z, &point->T};
    for (size_t coordinate = 0; coordinate < 4; coordinate++)
        for (size_t limb = 0; limb < 5; limb++)
            coordinates[coordinate]->limb[limb][lane] =
                vector->coordinate[coordinate][limb];
}

static int
equal_lane(
    const narya_edwards_point_x8 *got,
    const narya_edwards_point_x8 *want,
    size_t lane)
{
    return equal_field_lane(&got->X, &want->X, lane) &&
           equal_field_lane(&got->Y, &want->Y, lane) &&
           equal_field_lane(&got->Z, &want->Z, lane) &&
           equal_field_lane(&got->T, &want->T, lane);
}

static int
check_group(const decode_vector vectors[8], size_t count, size_t first_index)
{
    uint8_t encoded[8 * 32] = {0};
    narya_edwards_point_x8 want = {0};
    uint8_t active = 0;
    uint8_t expected_valid = 0;

    for (size_t lane = 0; lane < count; lane++) {
        memcpy(&encoded[lane * 32], vectors[lane].encoded, 32);
        set_expected_lane(&want, lane, &vectors[lane]);
        active |= (uint8_t)(UINT8_C(1) << lane);
        if (vectors[lane].valid)
            expected_valid |= (uint8_t)(UINT8_C(1) << lane);
    }

    /* Inactive expected lanes are the documented fail-closed identity. */
    for (size_t lane = count; lane < 8; lane++) {
        want.Y.limb[0][lane] = 1;
        want.Z.limb[0][lane] = 1;
    }

    narya_edwards_point_x8 got;
    memset(&got, 0xa5, sizeof(got));
    const uint8_t valid = narya_edwards_decode_x8(&got, encoded, active);
    if (valid != expected_valid) {
        fprintf(stderr,
            "decode fixture mask mismatch at vector %zu: got=%02x want=%02x\n",
            first_index, valid, expected_valid);
        return 0;
    }
    for (size_t lane = 0; lane < 8; lane++) {
        if (!equal_lane(&got, &want, lane)) {
            fprintf(stderr,
                "decode fixture coordinate mismatch at vector %zu lane %zu\n",
                first_index + lane, lane);
            return 0;
        }
    }
    return 1;
}

int
main(int argc, char **argv)
{
    if (argc != 2) {
        fprintf(stderr, "usage: %s VECTOR_FILE\n", argv[0]);
        return 2;
    }
    if (!narya_r51x8_available()) {
        if (getenv("NARYA_REQUIRE_IFMA") != NULL) {
            fputs("FAIL: native IFMA execution was required but unavailable\n", stderr);
            return 1;
        }
        puts("SKIP: full AVX-512 IFMA feature set is unavailable");
        return 0;
    }

    FILE *input = fopen(argv[1], "r");
    if (input == NULL) {
        perror(argv[1]);
        return 2;
    }

    char line[1024];
    decode_vector group[8];
    size_t group_count = 0;
    size_t vector_count = 0;
    size_t line_number = 0;
    int ok = 1;
    while (fgets(line, sizeof(line), input) != NULL) {
        line_number++;
        if (line[0] == '#' || line[0] == '\n')
            continue;
        if (!parse_vector(line, &group[group_count])) {
            fprintf(stderr, "invalid fixture syntax at line %zu\n", line_number);
            ok = 0;
            break;
        }
        group_count++;
        if (group_count == 8) {
            if (!check_group(group, group_count, vector_count)) {
                ok = 0;
                break;
            }
            vector_count += group_count;
            group_count = 0;
        }
    }
    if (ok && ferror(input)) {
        perror(argv[1]);
        ok = 0;
    }
    if (ok && group_count != 0) {
        if (!check_group(group, group_count, vector_count))
            ok = 0;
        else
            vector_count += group_count;
    }
    fclose(input);

    if (!ok || vector_count == 0)
        return 1;
    printf("PASS: %zu pinned permissive-decoder vectors\n", vector_count);
    return 0;
}
