/* Copyright 2026 Overclock Validator; SPDX-License-Identifier: Apache-2.0 */
#include "narya_ed25519_asm.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

enum {
    lanes = 8,
    batch_maximum = NARYA_VERIFY_STRICT_BATCH_MAX,
    maximum_message = 4096,
    expected_cases = 2954
};

typedef struct external_case {
    char name[192];
    uint8_t public_key[32];
    uint8_t signature[64];
    uint8_t message[maximum_message];
    size_t message_length;
    int expected;
} external_case;

static int
hex_nibble(char value)
{
    if (value >= '0' && value <= '9')
        return value - '0';
    if (value >= 'a' && value <= 'f')
        return value - 'a' + 10;
    return -1;
}

static int
parse_hex(uint8_t *output, size_t *output_size, size_t capacity, const char *hex)
{
    const size_t length = strlen(hex);
    if ((length & 1U) != 0 || length / 2 > capacity)
        return 0;
    for (size_t index = 0; index < length / 2; index++) {
        const int high = hex_nibble(hex[2 * index]);
        const int low = hex_nibble(hex[2 * index + 1]);
        if (high < 0 || low < 0)
            return 0;
        output[index] = (uint8_t)(high << 4 | low);
    }
    *output_size = length / 2;
    return 1;
}

/*
 * The committed corpus is generated by encoding/json with a fixed schema.
 * This deliberately small extractor accepts only that schema: it is a test
 * fixture parser, not a general JSON implementation.
 */
static int
json_string(
    const char *line,
    const char *field,
    char *output,
    size_t output_capacity)
{
    char marker[96];
    const int marker_length = snprintf(marker, sizeof(marker), "\"%s\":\"", field);
    if (marker_length < 0 || (size_t)marker_length >= sizeof(marker))
        return 0;
    const char *start = strstr(line, marker);
    if (start == NULL)
        return 0;
    start += (size_t)marker_length;
    const char *end = strchr(start, '"');
    if (end == NULL || (size_t)(end - start) >= output_capacity)
        return 0;
    memcpy(output, start, (size_t)(end - start));
    output[end - start] = '\0';
    return 1;
}

static int
parse_case(const char *line, external_case *item)
{
    char public_hex[65];
    char signature_hex[129];
    char message_hex[2 * maximum_message + 1];
    size_t size;
    if (!json_string(line, "name", item->name, sizeof(item->name)) ||
        !json_string(line, "public_key", public_hex, sizeof(public_hex)) ||
        !json_string(line, "message", message_hex, sizeof(message_hex)) ||
        !json_string(line, "signature", signature_hex, sizeof(signature_hex)) ||
        !parse_hex(item->public_key, &size, sizeof(item->public_key), public_hex) ||
        size != sizeof(item->public_key) ||
        !parse_hex(item->signature, &size, sizeof(item->signature), signature_hex) ||
        size != sizeof(item->signature) ||
        !parse_hex(item->message, &item->message_length,
                   sizeof(item->message), message_hex))
        return 0;

    const char *boolean = strstr(line, "\"narya_dalek_strict\":");
    if (boolean == NULL)
        return 0;
    boolean += strlen("\"narya_dalek_strict\":");
    if (strncmp(boolean, "true", 4) == 0)
        item->expected = 1;
    else if (strncmp(boolean, "false", 5) == 0)
        item->expected = 0;
    else
        return 0;
    return 1;
}

static int
run_group(
    const external_case group[lanes],
    size_t count,
    void *workspace,
    size_t workspace_size)
{
    uint8_t public_key[lanes * 32] = {0};
    uint8_t signature[lanes * 64] = {0};
    const uint8_t *message[lanes] = {0};
    size_t message_length[lanes] = {0};
    uint8_t expected = 0;
    const uint8_t active = count == lanes
        ? UINT8_C(0xff)
        : (uint8_t)((UINT16_C(1) << count) - 1U);

    for (size_t lane = 0; lane < count; lane++) {
        memcpy(&public_key[lane * 32], group[lane].public_key, 32);
        memcpy(&signature[lane * 64], group[lane].signature, 64);
        message[lane] = group[lane].message;
        message_length[lane] = group[lane].message_length;
        if (group[lane].expected)
            expected |= (uint8_t)(UINT8_C(1) << lane);
    }

    uint8_t verdict = UINT8_C(0xa5);
    const narya_status status = narya_ed25519_verify_strict_x8(
        &verdict, public_key, signature, message, message_length, active,
        workspace, workspace_size);
    if (status != NARYA_OK) {
        fprintf(stderr, "external group API status=%d\n", (int)status);
        return 0;
    }
    if (verdict != expected) {
        fprintf(stderr, "external verdict=%02x want=%02x\n", verdict, expected);
        for (size_t lane = 0; lane < count; lane++)
            if (((verdict ^ expected) & (UINT8_C(1) << lane)) != 0)
                fprintf(stderr, "  lane %zu: %s\n", lane, group[lane].name);
        return 0;
    }
    return 1;
}

static int
run_batch(
    const external_case batch[batch_maximum],
    size_t count,
    void *x8_workspace,
    size_t x8_workspace_size,
    void *batch_workspace,
    size_t batch_workspace_size)
{
    uint8_t public_key[batch_maximum * 32] = {0};
    uint8_t signature[batch_maximum * 64] = {0};
    const uint8_t *message[batch_maximum] = {0};
    size_t message_length[batch_maximum] = {0};
    uint64_t expected = 0;
    for (size_t item = 0; item < count; item++) {
        memcpy(&public_key[item * 32], batch[item].public_key, 32);
        memcpy(&signature[item * 64], batch[item].signature, 64);
        message[item] = batch[item].message;
        message_length[item] = batch[item].message_length;
        if (batch[item].expected)
            expected |= UINT64_C(1) << item;
    }

    uint64_t verdict = UINT64_C(0xa5a5a5a5a5a5a5a5);
    const narya_status status = narya_ed25519_verify_strict_batch(
        &verdict, public_key, signature, message, message_length, count,
        batch_workspace, batch_workspace_size);
    if (status != NARYA_OK || verdict != expected) {
        fprintf(stderr,
            "external batch count=%zu status=%d verdict=%016llx want=%016llx\n",
            count, (int)status, (unsigned long long)verdict,
            (unsigned long long)expected);
        for (size_t item = 0; item < count; item++)
            if (((verdict ^ expected) & (UINT64_C(1) << item)) != 0)
                fprintf(stderr, "  item %zu: %s\n", item, batch[item].name);
        return 0;
    }

    /* The established x8 API remains an independent grouping oracle. */
    for (size_t offset = 0; offset < count; offset += lanes) {
        const size_t remaining = count - offset;
        const size_t group_count = remaining < lanes ? remaining : lanes;
        if (!run_group(&batch[offset], group_count,
                       x8_workspace, x8_workspace_size))
            return 0;
    }
    return 1;
}

int
main(int argc, char **argv)
{
    if (argc != 2) {
        fprintf(stderr, "usage: %s EXTERNAL_JSONL\n", argv[0]);
        return 1;
    }

    FILE *file = fopen(argv[1], "r");
    if (file == NULL) {
        perror("open external corpus");
        return 1;
    }

    const int native = narya_r51x8_available();
    const char *required = getenv("NARYA_REQUIRE_IFMA");
    if (!native && required != NULL && required[0] == '1') {
        fputs("AVX-512 IFMA required but unavailable\n", stderr);
        fclose(file);
        return 1;
    }

    void *x8_workspace = NULL;
    void *batch_workspace = NULL;
    const size_t x8_workspace_size =
        narya_ed25519_verify_strict_x8_workspace_size();
    const size_t batch_workspace_size =
        narya_ed25519_verify_strict_batch_workspace_size();
    if (native) {
        x8_workspace = malloc(x8_workspace_size);
        batch_workspace = malloc(batch_workspace_size);
        if (x8_workspace == NULL || batch_workspace == NULL) {
            free(x8_workspace);
            free(batch_workspace);
            fclose(file);
            return 1;
        }
    }

    external_case batch[batch_maximum] = {0};
    size_t batch_count = 0;
    size_t total = 0;
    char line[2 * maximum_message + 1024];
    while (fgets(line, sizeof(line), file) != NULL) {
        if (strchr(line, '\n') == NULL && !feof(file)) {
            fputs("external corpus line exceeds parser capacity\n", stderr);
            free(x8_workspace);
            free(batch_workspace);
            fclose(file);
            return 1;
        }
        if (!parse_case(line, &batch[batch_count])) {
            fprintf(stderr, "invalid external corpus record %zu\n", total + 1);
            free(x8_workspace);
            free(batch_workspace);
            fclose(file);
            return 1;
        }
        batch_count++;
        total++;
        /*
         * Exercise every corpus item through the packed singleton route and
         * every adjacent pair through the two-chain packed route. The wider
         * 64-item pass below remains the independent x8/batch-finalizer gate.
         */
        if (native &&
            (!run_batch(
                 &batch[batch_count - 1], 1, x8_workspace,
                 x8_workspace_size, batch_workspace, batch_workspace_size) ||
             (batch_count >= 2 &&
              !run_batch(
                  &batch[batch_count - 2], 2, x8_workspace,
                  x8_workspace_size, batch_workspace,
                  batch_workspace_size)))) {
            free(x8_workspace);
            free(batch_workspace);
            fclose(file);
            return 1;
        }
        if (batch_count == batch_maximum) {
            if (native && !run_batch(
                    batch, batch_count, x8_workspace, x8_workspace_size,
                    batch_workspace, batch_workspace_size)) {
                free(x8_workspace);
                free(batch_workspace);
                fclose(file);
                return 1;
            }
            batch_count = 0;
        }
    }
    if (ferror(file) || total != expected_cases ||
        (native && batch_count != 0 &&
         !run_batch(batch, batch_count, x8_workspace, x8_workspace_size,
                    batch_workspace, batch_workspace_size))) {
        if (total != expected_cases)
            fprintf(stderr, "external corpus cases=%zu want=%d\n", total, expected_cases);
        free(x8_workspace);
        free(batch_workspace);
        fclose(file);
        return 1;
    }

    free(x8_workspace);
    free(batch_workspace);
    fclose(file);
    if (native)
        printf("PASS: %zu RFC/CCTV/Wycheproof and boundary vectors\n", total);
    else
        printf("SKIP native verdicts: validated %zu external records\n", total);
    return 0;
}
