#!/usr/bin/env python3
"""Extract exact transpose function bytes from relocation-free ELF objects.

Unlike the multiplier proof fixture, these two leaves reference no external or
RIP-relative data. Their ET_REL `.text` bytes are therefore already the bytes a
linker copies into a consumer. The extractor rejects any relocation section
targeting the function's executable section before emitting Lean input.

This is an artifact-identity layer, not an instruction decoder or execution
proof. The generated bytes are intended to feed the restricted Lean decoder.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import sys
from pathlib import Path

from generate_r51_object_bytes import (
    ET_REL,
    SHF_EXECINSTR,
    SHT_PROGBITS,
    STT_FUNC,
    Elf,
    fail,
    nat_list,
)


ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "formal/lean/NaryaFormal/GeneratedTransposeObjectBytes.lean"
DEFAULT_PROJECTIVE = ROOT / "build/proof/projective_niels_transpose_x8.o"
DEFAULT_AFFINE = ROOT / "build/proof/affine_niels_transpose_x8.o"
SHT_RELA = 4
SHT_REL = 9


def extract(path: Path, symbol_name: str) -> bytes:
    data = path.read_bytes()
    elf = Elf(data, allowed_types=(ET_REL,))
    symbol, code = elf.symbol_bytes(
        symbol_name, expected_size=None, executable=True
    )
    if (symbol.info & 0xF) != STT_FUNC or symbol.size == 0:
        fail(f"{symbol_name} is not a nonempty STT_FUNC symbol")
    section = elf.sections[symbol.section_index]
    if section.kind != SHT_PROGBITS or not (section.flags & SHF_EXECINSTR):
        fail(f"{symbol_name} is not in executable PROGBITS")
    relocations = [
        candidate
        for candidate in elf.sections
        if candidate.kind in (SHT_RELA, SHT_REL)
        and candidate.info == symbol.section_index
        and candidate.size != 0
    ]
    if relocations:
        names = ", ".join(candidate.name for candidate in relocations)
        fail(f"{symbol_name} executable section has relocations: {names}")
    return code


def render(projective_path: Path, affine_path: Path) -> str:
    projective = extract(
        projective_path, "narya_projective_niels_transpose_x8_asm"
    )
    affine = extract(
        affine_path, "narya_affine_niels_transpose_x8_asm"
    )
    return f"""/-
Copyright 2026 Overclock Validator
SPDX-License-Identifier: Apache-2.0

Generated by tools/generate_transpose_object_bytes.py from relocation-free
ELF64 x86-64 objects. Do not edit by hand. These are exact assembled function
bytes, not decoded instructions and not an execution proof.

Projective symbol SHA-256: {hashlib.sha256(projective).hexdigest()}
Affine symbol SHA-256: {hashlib.sha256(affine).hexdigest()}
-/

namespace NaryaFormal.TransposeObject

def projectiveSymbolSize : Nat := {len(projective)}
def projectiveSymbolBytes : List Nat := {nat_list(projective)}

def affineSymbolSize : Nat := {len(affine)}
def affineSymbolBytes : List Nat := {nat_list(affine)}

end NaryaFormal.TransposeObject
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--projective", type=Path, default=DEFAULT_PROJECTIVE)
    parser.add_argument("--affine", type=Path, default=DEFAULT_AFFINE)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    generated = render(arguments.projective, arguments.affine)
    if arguments.output is not None:
        arguments.output.write_text(generated, encoding="ascii")
        return
    if arguments.check:
        committed = GENERATED.read_text(encoding="ascii")
        if committed != generated:
            sys.stderr.writelines(
                difflib.unified_diff(
                    committed.splitlines(keepends=True),
                    generated.splitlines(keepends=True),
                    fromfile=str(GENERATED),
                    tofile="generated transpose object bytes",
                )
            )
            fail("transpose object bytes differ from committed Lean artifact")
        print("OK: assembled transpose symbols match committed Lean input")
        return
    sys.stdout.write(generated)


if __name__ == "__main__":
    main()
